HW2 is completed
sealmog/go_home_work pull request #2
Opened 2022-11-08 16:35 UTC by sealmog

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-11-08 17:36 UTC, Nikscorp requested changes
Здравствуйте!

Работ хорошая, корректно реализован функционал для строк, состоящих из ascii символов. Код достаточно лаконичен.

Но так как согласно ТЗ на вход подаются произвольные строки — код работает некорректно на части сценариев.

Я оставил подробные замечания в комментариях к PR. Чтобы зачесть работу — нужно будет исправить критические замечания.

>  **P.S.**
> 
> Нотация:
> 
> - CRIT: критическое замечание ведущее к значительному снижению баллов
> - WARN: некритическое замечание ведущее к незначительному снижению баллов (часто по критерию чистого кода / аккуратности)
> - NB: nota bene — что-то на что нужно обратить внимание (например в реальных проектах), совет, к снижению баллов не ведет
> - GREAT: часть проекта, которую хочется похвалить, выделить
> 
> Проверяющие тоже люди — в своих замечаниях я могу что-то упустить или ошибиться, в случае если вы не согласны с замечаниями — не стесняйтесь их оспаривать.
> 
> Если что-то нужно перепроверить, заапрувить, принять инвайт, поднять оценку, то прошу следовать данной последовательности:
> 
> 1. Написать в чате со мной с ДЗ на сайте ОТУС-а и перекинуть ДЗ на меня со статусом "Нужно проверить"
> 2. Написать на GitHub-е
> 3. Продублировать мне сообщение в корпоративном Slack-е: (Nikita Voynov)

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +			prev := s[pos-1 : pos]
CRIT:
`pos-1` использовать некорректно, так как один символ может занимать более одного байта. Например, попробуйте передать на ввод программе кириллицу: `{input: "я4", expected: "яяяя"}` — такой тест упадет.

Получается покрытие юнит тестами также не полное

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		if unicode.IsDigit(char) {
WARN:
Использование `unicode.IsDigit`. Несмотря на то, что в задании указана рекомендация по использованию данной функции я советовал бы отнестись к ней с осторожностью. Помимо арабских цифр `0, 1 ... 9` она трактует как цифры также иные символы, например отсюда https://www.fileformat.info/info/unicode/category/Nd/list.htm . Если вы трактуете задание таким образом, то необходимо покрыть данный функционал юнит-тестами, также прошу учесть, что с такой трактовкой ваш код также не будет работать, так как digit-символы вне `0...9` не смогут привестись к int с помощью `strconv.Atoi`, пример: https://go.dev/play/p/zPCRUQsqPuG. Я обсужу с руководителем курса рекомендацию по использованию `unicode.IsDigit`. Я рекомендую проверять символы простым сравнением с байтами `0` и `9`, а к инту приводить простым вычитанием из символа `'0'` с расширением типа.

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	var result []string
NB: рекомендую использовать `strings.Builder` — это эффективнее и удобнее

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	//nolint:nestif
NB:
литер говорит дело — лучше избегать излишней вложенности. Например с помощью continue

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +func TestLen(t *testing.T) {
зачем проверять длину, если можно проверить сам результат как в тесте выше?

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +			require.Equal(t, true, ok)
что проверяет этот тест? Что функция возвращает string? Мы и так это знаем

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +		{input: "a0", expected: ""},
не хватает тестов на символы, занимающие в Юникоде более 1 байта — кириллица, иероглифы, эмоджи и тд

2022-11-08 17:36 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	if _, err := strconv.Atoi(s[0:1]); err == nil {
NB: обычно обрабатывают `err != nil` внутри if, а остальное уже во внешней области

2022-12-03 19:09 UTC, sealmog commented on hw02_unpack_string/unpack.go
> +			prev := s[pos-1 : pos]
Спасибо, поправил.

2022-12-03 19:09 UTC, sealmog commented on hw02_unpack_string/unpack.go
> +		if unicode.IsDigit(char) {
Спасибо, поправил.

2022-12-03 19:10 UTC, sealmog commented on hw02_unpack_string/unpack.go
> +	var result []string
Спасибо, поправил.

2022-12-03 19:10 UTC, sealmog commented on hw02_unpack_string/unpack.go
> +	//nolint:nestif
Спасибо, поправил.

2022-12-04 17:07 UTC, Nikscorp approved these changes
Добрый вечер!

Работа зачтена, но 1 балл вычитаю за замечания, указанные в PR.
Текущая оценка: 9 баллов.

2022-12-04 17:07 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +func IsDigit(s string) bool {
WARN: Почему тут строка принимается, а не `rune`?

2022-12-04 17:07 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	if IsDigit(s[0:1]) {
WARN: все еще опасно обращаться по индексам к строке. Лучше приведите ее к массиву рун и там смотрите на первую руну.

2022-12-04 17:07 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +				b.WriteRune(prev)
NB: для этого есть `strings.Repeat`

2022-12-04 17:07 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +				b.Reset()
NB: очень грязно

2022-12-04 17:07 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +		{input: "১২৩", expected: "১২৩"},
NB: не вижу смысла выносить эти кейсы из основного табличного. Хотите дать им более осмысленное имя — просто передайте его в `tc.Run`

2022-12-09 17:32 UTC, Nikscorp approved these changes
Замечания исправлены.
Повышаю оценку до максимального балла.

2022-12-10 11:07 UTC, merged