HW4 is completed
sealmog/go_home_work pull request #4
Opened 2023-01-15 15:54 UTC by sealmog

2023-01-16 23:49 UTC, Nikscorp requested changes
Добрый день.
Оставил замечания к работе.
В настоящий момент работу принять не могу.

> **P.S.**
> 
> Нотация:
> 
> - CRIT: критическое замечание ведущее к значительному снижению баллов
> - WARN: некритическое замечание ведущее к незначительному снижению баллов (часто по критерию чистого кода / аккуратности)
> - NB: nota bene — что-то на что нужно обратить внимание (например в реальных проектах), совет, к снижению баллов не ведет
> - GREAT: часть проекта, которую хочется похвалить, выделить
> 
> Проверяющие тоже люди — в своих замечаниях я могу что-то упустить или ошибиться, в случае если вы не согласны с замечаниями — не стесняйтесь их оспаривать.
> 
> Если что-то нужно перепроверить, заапрувить, принять инвайт, поднять оценку, то прошу следовать данной последовательности:
> 
> 1. Написать в чате со мной с ДЗ на сайте ОТУС-а и перекинуть ДЗ на меня со статусом "Нужно проверить"
> 2. Написать на GitHub-е
> 3. Продублировать мне сообщение в корпоративном Slack-е: (Nikita Voynov)

2023-01-16 23:49 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +		c.purge()
WARN: а зачем это выносить в отдельную функцию? Там 3 строки и она больше нигде не используется.

2023-01-16 23:49 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +	return element.Value.(*cacheItem).value, true
CRIT: а где здесь логика то LRU? Перечитайте, пожалуйста, задание, там по шагам расписано, что должен делать метод `Get`

2023-01-16 23:49 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +		c.purge()
более того как-то неудачно выбрано место для данной проверки, не лучше ли это проверять сразу после `PushFront`?

2023-01-16 23:49 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +2) Реализация кэша на основе ранее написанного списка
NB: я бы это удалил или оформил это аккуартно и соотвественно конвенциям по комментированию методов и пакетов

2023-01-16 23:49 UTC, Nikscorp commented on hw04_lru_cache/cache.go
> +	return element.Value.(*cacheItem).value, true
кстати, раз тесты проходят — значит и тестов написано недостаточно

2023-01-21 17:44 UTC, sealmog commented on hw04_lru_cache/cache.go
> +		c.purge()
поправил

2023-01-21 17:45 UTC, sealmog commented on hw04_lru_cache/cache.go
> +2) Реализация кэша на основе ранее написанного списка
удалил

2023-01-21 17:45 UTC, sealmog commented on hw04_lru_cache/cache.go
> +	return element.Value.(*cacheItem).value, true
поправил, дописал тесты

2023-01-25 04:53 UTC, Nikscorp approved these changes
Сергей, добрый день!

Теперь все хорошо, ставлю максимальный балл.

2023-01-25 16:48 UTC, merged